Increase requests for cluster-controller
The requests we set for the cluster-controller is too low and results in
`Exception in thread "Cluster-ReconciliationCycle"
java.lang.OutOfMemoryError: Garbage-collected heap size exceeded.`

We therefore need to increase the requests so that the controller can
properly reconcile all resources

Signed-off-by: Nicolas Bigler <nicolas.bigler@vshn.ch>